### ISSUE TITLE
Uploading PDF files

### ISSUE THREAD

**Issue by jorisnoo** [thomasvantuycom/flysystem-cloudinary#2]
Hi there,

First of all, thank you very much for your effort on this integration! I've successfully been able to use cloudinary as filesystem in Craft CMS.

I noticed that pdf files are being uploaded as 'raw' resources. If i, however, upload a pdf directly into cloudinary, it is treated as image. Now, when a pdf is uploaded directly through cloudinary (and being treated as image), it is treated as 'raw' file in craft. 

This leads to broken links: Linking to a pdf file always assumes 'raw', but for pdf files uploaded through cloudinary only 'image' as resource type will work.

Changing the behaviour in `pathToResourceType` seems tricky, since it would potentially break all existing pdf files.

I was just wondering, whether you'd have any idea or opinion on how to approach this. Many thanks!

**Comment by thomasvantuycom** [comment]
Hi Joris,

Thank you for bringing this to my attention. I'll address the behavior of `pathToResourceType` in this repository. Regarding the inconsistency between existing uploads done through Craft or directly in Cloudinary, it seems like we need to change the resource type to `image` for the PDFs that were incorrectly uploaded as `raw` files, and change their public ID. I'll either provide a script here or create a migration in the Craft plugin to resolve this issue.

Which version of Craft are you using?

**Comment by jorisnoo** [comment]
Hi Thomas,
Many thanks for your response — that seems to be the ideal solution!
I'm using Craft CMS 4.9.5.

**Comment by thomasvantuycom** [comment]
Regarding the misidentified assets, Cloudinary doesn't permit changing the resource type. Therefore, the only solution is to delete and re-upload the affected assets. Since this could lead to problems if the upload date is significant, I won't be incorporating this as a migration in Craft. However, I do have a small script in Node that might be useful to you if needed.

```js
import { v2 as cloudinary } from 'cloudinary';

cloudinary.config({
    cloud_name: '...',
    api_key: '...',
    api_secret: '...'
});

async function correctPdfResourceType(next_cursor) {
    const response = await cloudinary.search
        .expression('resource_type:raw AND format:pdf')
        .max_results(500)
        .next_cursor(next_cursor)
        .execute();

    if (response.resources.length > 0) {
        for (const resource of response.resources) {
            await cloudinary.uploader.upload(resource['secure_url'], {
                public_id: resource['public_id'].replace(/\.pdf$/, ''),
                asset_folder: resource['asset_folder'] ?? resource['folder'],
            });
        }

        await cloudinary.api.delete_resources(response.resources.map(resource => resource['public_id']), {
            resource_type: 'raw'
        })

        if (response['next_cursor']) {
            await correctPdfResourceType(response['next_cursor']);
        }
    }

}

await correctPdfResourceType();
console.log('Done!');
```

**Comment by jorisnoo** [comment]
Thank you @thomasvantuycom , this worked like a charm! :heart:
